### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Guillaume-succubus** [EnricoPicci/ng-joystick#4]
I cloned the repo then cd into it and use npm install.

I got this error : 

from ../../nan/nan.h:53,
                 from ../src/binding.cpp:1:
../../nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../../nan/nan_object_wrap.h:124:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
  124 |     assert(wrap->handle_.IsNearDeath());

resulting in : 

Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/guillaume/stage/testJoysticks/ng-joystick/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

Do you now how to fix ?

**Comment by EnricoPicci** [comment]
Looks like a  problem of Node version and compatibility with the npm packages required.
